fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
      - id: pretty-format-json
      - id: trailing-whitespace
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.1
    hooks:
     - id: pyupgrade
  - repo: local
    hooks:
      - id: system
        name: isort
        entry: sh -c 'poetry run isort .'
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: black
        entry: sh -c 'poetry run black .'
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: MyPy
        entry: sh -c 'poetry run mypy default'
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: Pylint
        entry: sh -c 'poetry run pylint -j 0 default'
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: Pytest
        entry: sh -c 'poetry run pytest default'
        pass_filenames: false
        language: system
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.3.1
    hooks:
    - id: nbqa-black
      types: [jupyter]
      additional_dependencies: [black]
    - id: nbqa-pyupgrade
      additional_dependencies: [pyupgrade]
    - id: nbqa-isort
      additional_dependencies: [isort==5.6.4]
    - id: nbqa-mypy
      types: [jupyter]
      additional_dependencies: [mypy]
    - id: nbqa-pylint
      name: nbqa-pylint
      types: [jupyter]
      additional_dependencies: [pylint]
